# Generated by Django 2.2 on 2021-05-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='نام فیلم')),
                ('director', models.CharField(max_length=64, verbose_name='کارگردان')),
                ('year', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('length', models.PositiveIntegerField(verbose_name='زمان فیلم')),
                ('country', models.CharField(max_length=64, verbose_name='کشور سازنده')),
                ('language', models.CharField(max_length=32, verbose_name='زبان فیلم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover', models.ImageField(upload_to='movie/covers/', verbose_name='تصویر فیلم')),
            ],
        ),
    ]
