# Generated by Django 2.2 on 2021-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20210524_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, verbose_name='نام سینما')),
                ('city', models.CharField(max_length=254, verbose_name='شهر')),
                ('capacity', models.IntegerField(verbose_name='گنچایش سینما')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
        ),
    ]
