# Generated by Django 2.2 on 2021-05-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ اکران')),
                ('end_time', models.DateTimeField(verbose_name='تاریخ پایان اکران')),
                ('price', models.BigIntegerField(verbose_name='قیمت بلیت')),
                ('salabel_seats', models.IntegerField(verbose_name='صندلی های قابل فروش')),
                ('free_seats', models.IntegerField(verbose_name='صندلی های خالی')),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیت'), (3, 'بلیت ها تمام شد'), (4, 'فروش بلیت بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], verbose_name='وضعیت سانس')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='ticketing.Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='ticketing.Movie')),
            ],
        ),
    ]
